<<<<<<< HEAD
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: jwr9484
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
=======
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: jwr9484
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
>>>>>>> 58429fcd7179c341c9b1ac4cf4c68aa9807ca3f3
        default_batch_fetch_size: 1000